### ISSUE TITLE
Duration not changing when specified during export

### ISSUE THREAD

**Issue by DoricDream** [Alexco500/sidplay5#18] opened 2023-04-25 21:30 UTC
Selecting the duration to export to an audio file does not work. 

I tried to export 1:50 of a particular file to mp3, but it would never actually affect the duration of the export - it would always export the length of of the current track, or 3:00 if the track has no specified length.

**Comment by Alexco500** [comment] 2023-04-26 15:47
Just did a quick test, but I couldn't reproduce that. Was the song part of the HVSC? Or a song somewhere on disk?
Any special settings regarding export?

**Comment by Alexco500** [comment] 2023-10-08 19:47
Ahh, sorry, I guess I found the issue :-) Should be fixed in the next release.

**Closed** 2023-10-12 19:22 UTC
